apiVersion: v1
kind: ConfigMap
metadata:
  name: autoreparos-grafana-providers-config
  labels:
    {{- include "observability.labels" . | nindent 4 }}
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'AutoReparos Dashboards'
        orgId: 1
        folder: 'AutoReparos'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/provisioning/dashboards/json
