apiVersion: v1
kind: Service
metadata:
  name: autoreparos-otel-collector
  labels:
    app: autoreparos-otel-collector
    {{- include "observability.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: autoreparos-otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 8889
      targetPort: 8889
