apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoreparos-prometheus
  labels:
    app: autoreparos-prometheus
    {{- include "observability.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoreparos-prometheus
  template:
    metadata:
      labels:
        app: autoreparos-prometheus
    spec:
      containers:
        - name: autoreparos-prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          args: ["--config.file=/etc/prometheus/prometheus.yml"]
          ports:
            - containerPort: 9090
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: config
          configMap:
            name: autoreparos-prometheus-config
