{
 "title": "AutoReparos - EKS Cluster & HPA Monitor",
 "tags": [
  "soat",
  "tech-challenge"
 ],
 "panels": [
  {
   "title": "Quantidade de Réplicas da API (HPA)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"default\", deployment=\"autoreparos-k8s-api\"}",
     "legendFormat": "Réplicas Ativas"
    }
   ]
  },
  {
   "title": "Uso de CPU por Pod (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", container=\"k8s\"}[2m])) by (pod) * 100",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  },
  {
   "title": "Uso de Memória por Pod (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", container=\"k8s\"}) by (pod) / 1024 / 1024",
     "legendFormat": "{{`{{pod}}`}}"
    }
   ]
  }
 ]
}