apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}-secret
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.password | b64enc | quote }}
