apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secrets
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  Jwt__Secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  SeedUser__Password: {{ .Values.secrets.seedUserPassword | b64enc | quote }}
  AprovacaoToken__Secret: {{ .Values.secrets.aprovacaoTokenSecret | b64enc | quote }}
  SendGrid__ApiKey: {{ .Values.secrets.sendGridApiKey | b64enc | quote }}
